export const ADD_CHURRAS = "ADD_CHURRAS";
export const EDIT_CHURRAS = "EDIT_CHURRAS";
export const DELETE_CHURRAS = "DELETE_CHURRAS";

export const ADD_PARTICIPANT = "ADD_PARTICIPANT";
export const EDIT_PARTICIPANT = "EDIT_PARTICIPANT";
export const DELETE_PARTICIPANT = "DELETE_PARTICIPANT";
